version: 2.1
orbs:
  cypress: cypress-io/cypress@1

workflows:
  build:
    jobs:
      - project/build:
        build: "npm run build"
      - cypress/run:
        requires:
          "project/build"
