version: 2.1
orbs:
  cypress: cypress-io/cypress@1

workflows:
  build:
    jobs:
      - cypress/install:
          name: "cypress/install"
          build: "npm run build"
      - cypress/run:
          requires:
            - "cypress/install"

